### ISSUE TITLE
How do I pass a preprocessor flag for xcodebuild?

### ISSUE THREAD

**Issue by udaypandey** [nomad/shenzhen#121]
I am trying to pass preprocesser directivies from the command line. I m trying to add GCC_PREPROCESSOR_DEFINITIONS to the build command, but this does not seem to have any effect. 

A quick glance at the code. I think the extra parameters are left in args param in file commands/build.rb and args param is not passed to xcodebuild.

ipa build  --workspace Abc.xcworkspace \
               --scheme Abc \
               --configuration Adhoc \
               --destination build \
               --verbose \
                GCC_PREPROCESSOR_DEFINITIONS='XXX_SPIKE=1'

**Comment by dvkch** [comment]
Using --xcargs with whatever after seems to always result in this error:

`invalid option: --xcargs`

Any suggestion?
