### ISSUE TITLE
Add support for Crashlytics Beta

### ISSUE THREAD

**Issue by Leandros** [nomad/shenzhen#143]
Through `Crashlytics.framework` you are able to upload a build via command line

```
Crashlytics.framework/submit <API_KEY> <BUILD_SECRET> -ipaPath /path/to/my.ipa -emails TestEmail@crashlytics.com,AmazingTester@twitter.com -notesPath ~/Notes/ReleaseNotes.txt -groupAliases ﻿GroupAlias,GroupAlias2﻿
```

[More info](http://support.crashlytics.com/knowledgebase/articles/370383-how-do-i-use-ios-build-servers-with-beta)

**Comment by deepumukundan** [comment]
Would love to see this integrated with Fabric by crashlytics
