### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by max-mapper** [nomad/shenzhen#16]
using xcode 4.5 on mac os 10.7.4

upon doing `ipa build` I get an error like this:

Failed to load dependencies output contents from ``/Users/user/Library/Developer/Xcode/DerivedData/App-dhhhgbggewxkjrhdzbllaidjdkhk/Build/Intermediates/App.build/Ad-Hoc-iphoneos/App.build/Objects-normal/armv7/DatePicker.d''

Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “DatePicker.d” couldn’t be opened because there is no such file."

NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *, void (^)(NSString *))

there is however a `DatePicker.dia` file in that folder. not sure what I might be doing wrong -- thanks!

**Comment by soheil** [comment]
Also if you're using xcode beta you need to change your command line version to point to it:

`sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`
