### ISSUE TITLE
Include Build Number in ipa info command

### ISSUE THREAD

**Issue by skela** [nomad/shenzhen#160]
Would it be possible to include the build number in the ipa info output?
At this point its only showing version, which is the CFBundleShortVersionString.
Could it also output the build number (CFBundleVersion) below it?

**Comment by sebyddd** [comment]
For anyone still looking to print the build number, I put up a small bash function to unzip the .ipa in a temporary folder, extract the Build Version & Number and remote the generated Payload folder.

```
    # Display build version number
    mkdir $TMPDIR/temp-payload
	unzip -q APPNAME.ipa -d $TMPDIR/temp-payload
	BUNDLE_VERSION=$(defaults read $TMPDIR/temp-payload/Payload/APPNAME.app/Info.plist CFBundleShortVersionString)
	BUILD_NUMBER=$(defaults read $TMPDIR/temp-payload/Payload/APPNAME.app/Info.plist CFBundleVersion)
	print "iOS Build – $BUNDLE_VERSION ($BUILD_NUMBER)\n"
	rm -rf $TMPDIR/temp-payload
```

Result: 
![screen shot 2016-08-24 at 22 04 28](https://cloud.githubusercontent.com/assets/5271150/17944272/b13cb9a0-6a47-11e6-923c-6b6d7959237d.png)
