### ISSUE TITLE
beta entitlement missing

### ISSUE THREAD

**Issue by neugebap** [nomad/shenzhen#165]
I submitted an application to iTunes Connect for review and I notice that the build that I submitted has an issue associated with it saying that:

Build XXX does not contain the correct beta entitlement.

I have already regenerated my provisioning profile and double checked that it contains the entitlement beta-reports-active = true.

Any advice?

**Comment by qwertme** [comment]
I am getting this same issue, ipa info reports => beta-reports-active: true and yet => https://www.evernote.com/shard/s74/sh/32d40816-1716-4526-9eb4-9d749548aa1d/db25cd97a411ac6a6c3615094283d4c2

**Comment by staxmanade** [comment]
When I use `ipa build...` and upload to iTunesConnect I get the beta entitlement missing issue. But when I archive through xcode and upload through xcode, it is working.

Has anyone worked around this? Would be nice to automate this (I have [fasttools](http://fastlane.tools/) running the process (but not having TestFlight Beta is a bit annoying...)

**Comment by TheNathanBlack** [comment]
I'm having the same trouble and it seems to be related to `ipa build` settings and not being able to (or not knowing) how to `--embed` the proper provision. Maybe a bit more clarity on how to find the provisioning profiles and embed them appropriately?

**Comment by joemasilotti** [comment]
Have you generated a new signing certificate since the migration to Apple
TestFlight? I ran into a similar issue a few months back. Regenerating on
the web added the correct beta entitlements key for me.

**Comment by staxmanade** [comment]
I have - and If I open up the mobileprovision file in day VIM it has the entitlement listed.

But when I use Shenzhen to build/send to itunes connect it reports that it's missing.

But sending it up with xcode does work. (But is not automated :()

**Comment by TheNathanBlack** [comment]
Yeah, I regenerated mine as well.

**Comment by qwertme** [comment]
I had only regenerated the provisioning profile not the certificate. I just now regenerated the certificate and provisioning profile, gave it a try and got the exact same error. ipa info on the generated file still reports "beta-reports-active: true"

**Comment by brianseeders** [comment]
This issue indeed seems to be with the xcode build tools, and not with Shenzhen.

I am experiencing the same issue and have burned a lot of brainpower today trying to figure out a way around it without having to manually deal with Entitlement files.

When submitting with Xcode, the Entitlements are automatically correct.

However, if you build from the command-line, rename the .ipa to .zip and extract it, and check the entitlements, they aren't the same as they would have been using Xcode.

When you use `ipa info`, it displays the Entitlements attached to the provisioning profile, not the app itself.

After building an app, do:
```bash
unzip xxx.ipa
codesign -d --entitlements :- Payload/xxx.app
```
And you will likely notice that "beta-reports-active" is missing.

I will update this thread if I find a good solution.

**Comment by brianseeders** [comment]
Here's what I did to get it working:

I generated an Entitlements.plist using the one distributed with the SDK as a template:
`plutil -convert xml1 -o - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/Entitlements.plist > Entitlements.plist`

I added this to it:
```xml
<key>beta-reports-active</key>
<true/>
```

Whenever I need to use it, I use this argument with `ipa build`:

```
--xcargs 'CODE_SIGN_ENTITLEMENTS="Entitlements.plist" CODE_SIGN_IDENTITY="iPhone Distribution: XXXXXXX (YYYYYY)"'
```

Even if you use the `-i` argument to specify an identity, you still need to put it in the xcargs, or you will get an error. Also, it needs to be the full string of the identity (whereas with `-i`, it can be a partial string)

My full command looks like this:
```bash
ipa build -w App.xcworkspace -s Scheme -m "XYZ.mobileprovision" -i "YYY" --xcargs 'CODE_SIGN_ENTITLEMENTS="Entitlements.plist" CODE_SIGN_IDENTITY="iPhone Distribution: XXX (YYY)"'
```

**Comment by williamsjj** [comment]
Can we get ipa modified to do @brianseeders  fix automatically?

**Comment by williamsjj** [comment]
Wanted to post and update... @brianseeders change is not needed to get this working. We were using our Ad-Hoc provisioning profile that we also use for HockeyApp and other non-App Store builds. That does not contain the beta entitlement and is the problem. You have to use your App Store provisioning profile which does contain the beta entitlement. We duplicated our Release configuration as Release_TestFlight and changed it to use our App Store provisioning profile and everything worked.

**Comment by qwertme** [comment]
@williamsjj I am passing in the profile I want (distribution) on the command line of ipa, using the -i and -m parameters. It does not work.
