### ISSUE TITLE
distribute:itunesconnect says upload was successful, but it never arrived

### ISSUE THREAD

**Issue by staxmanade** [nomad/shenzhen#172]
Thanks for this amazing tool!

I noticed that when I tried to use the itunesconnect distribution in conjunction with keychain password I could not get the tool to upload correctly.

I'm not sure, but think there may be 2 issues?

- [ ] Keychain passwords not retrieved correctly. (See below)
- [ ] `--verbose` output did not log all of the output of the uploader tool (leaving me to guess what was going wrong).

What I saw with the `--verbose` parameter was the following:

```
Found password in keychain for account: myiTunes@email.com
/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/bin/iTMSTransporter -m upload -f Package.itmsp -u myiTunes@email.com -p \#\<Security::GenericPassword:0x007fd1da96e8e0\>
Upload complete. You may want to double check iTunes Connect to make sure it was received correctly.
```

I'm not familiar with Ruby, but thought the `-p \#\<Security::GenericPassword:0x007fd1da96e8e0\>` looked suspect.

I wrote the following test script to test out password retrieval.

```
require 'security'
@account = 'myiTunes@email.com'
ITUNES_CONNECT_SERVER = 'Xcode:itunesconnect.apple.com'
pwd = Security::GenericPassword.find(:s => ITUNES_CONNECT_SERVER, :a => @account)
puts pwd
puts pwd.password
```

I noticed that the the output looks like

```
#<Security::GenericPassword:0x007f90250206b8>
REAL_PASSWORD_PRINTED_HERE
```

I would have submitted a pull request for the fix - but am not very strong with Ruby. 

Any thoughts?

**Comment by mattt** [comment]
You are correct: this issue is resolved by #171, which is integrated into the latest release. Apologies for the inconvenience.
