### ISSUE TITLE
Does Shenzhen supports Test as part of "ipa build"

### ISSUE THREAD

**Issue by DanCodez** [nomad/shenzhen#173]
Hi all,

I'm setting up a CI enviroment using Jenkins and I'd like to have Unit Tests run as well.   Is there anyway to perform unit testing as part of shenzhen ?  

Sorry if this has been covered somewhere else, but a quick google-fu for shenzhen and tests have not yielded any results.

**Comment by fatuhoku** [comment]
I get the impression that Shenzhen itself uses `xcodebuild`. If `xctool` is just a superset of `xcodebuild` surely Shenzhen should have an option for building with `xctool` instead?
