### ISSUE TITLE
Code-Sign Error with no ResourceRules.plist

### ISSUE THREAD

**Issue by TimKreger** [nomad/shenzhen#174]
Hi,
since upgrading to Yosemite I've been getting deprecation warnings when code signing. 

> Warning: --resource-rules has been deprecated in Mac OS X >= 10.10

However if I remove the ResourceRules.plist from the build settings I get the 

>error: /usr/bin/codesign --force --preserve-metadata=identifier,entitlements,resource-rules --sign XXXXXX --resource-rules=/var/folders/rk/pcq8_6b51gl1nn06f8vvq6q40000gn/T/tKi57OzA2z/Payload/EnsoMona.app/ResourceRules.plist /var/folders/rk/pcq8_6b51gl1nn06f8vvq6q40000gn/T/tKi57OzA2z/Payload/EnsoMona.app failed with error 1. Output: Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
Warning: --resource-rules has been deprecated in Mac OS X >= 10.10!

Is there anything I can do to avoid this or will it require a future update of shenzhen?

At the moment there is no real problem I'll just keep the ResourceRules.plist in place.

**Comment by mattt** [comment]
`--resource-rules` may be deprecated in Yosemite for App Store builds, Shenzhen is geared towards development distribution, so this is less of a concern.

Until either this is deprecated on all platforms or it does more than report a warning, this is a low-priority issue.
