### ISSUE TITLE
build error for Xcode6.1.1

### ISSUE THREAD

**Issue by tikidunpon** [nomad/shenzhen#176]
Hi, thanks for this tool!

I run a command "ipa build", but I got a following error message...

Maybe this is the same issue with [this](http://stackoverflow.com/questions/25001940/shenzen-ios-build-giving-error)

What am I doing wrong?

xcodebuild  MyApp.xcworkspace
2015-01-07 11:52:13.902 xcodebuild[3989:42121] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-6611/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7fd084558ad0 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
Object:   <IDESourceControlManager: 0x7fd0840d7e40>
Method:   -loadRepositories
Thread:   <NSThread: 0x7fd082c35910>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** ARCHIVE FAILED **

**Comment by KrauseFx** [comment]
> Missing extension: public.vcs.subversion

This error is caused by `xcodebuild`. Try building and archiving using Xcode, if that works, build using the `xcodebuild` command. 

Also, you can run run `shenzhen` in *verbose* mode: `ipa build --verbose` to get more information during compiling.

**Comment by mattt** [comment]
Thanks, @KrauseFx.
