### ISSUE TITLE
Specify filename of output .ipa

### ISSUE THREAD

**Issue by fatuhoku** [nomad/shenzhen#182]
Is it possible?

**Comment by KrauseFx** [comment]
As far as I know, you can only specify the output folder, but not the actual file name.

**Comment by fatuhoku** [comment]
It'd be great if it was possible! Then I could run two instances of `deliver` at the same time!

**Comment by KrauseFx** [comment]
You still can, if you just build the `ipa` files in different folders.

**Comment by egold** [comment]
Another issue is if the filename (product name + ".ipa") has spaces in it, it will mess up some other scripts that I'm trying to integrate with. It would be great if it let you override, something like --output-file="app.ipa"

**Comment by egold** [comment]
I've fixed the issue, and am about to make a pull request

**Comment by mattt** [comment]
Fixed by #183. Thanks again, @egold.

**Comment by egold** [comment]
Happy to help!
