### ISSUE TITLE
ipa files with spaces fail to submit to itunes connect

### ISSUE THREAD

**Issue by poscar** [nomad/shenzhen#184]
I'm getting this error when the ipa file name has a space:

1 package(s) were not uploaded because they had problems:
	Package.itmsp - Error Messages:
		ERROR ITMS-3000: "Line 6 column 55: character content of element "file_name" invalid; must be a string matching the regular expression "[^/: ]*" at XPath /package/software_assets/asset/data_file/file_name"

**Comment by egold** [comment]
FWIW I have submitted a Pull Request that allows you to specify the filename of the generated .ipa file. In the meantime if you clone my fork it might meet your needs. https://github.com/nomad/shenzhen/pull/183

**Comment by poscar** [comment]
I ended up just renaming the .ipa file in my build script after building.  Either way your pull request is a nice feature and should be merged.

I still think the actual bug of not supporting spaces in the filename should be fixed.

**Comment by KrauseFx** [comment]
The bug of not supporting spaces in the file names is caused by the `iTunes Transporter` and not by `shenzhen`. 

The output you posted
> 1 package(s) were not uploaded because they had problems:
Package.itmsp - Error Messages:
ERROR ITMS-3000: "Line 6 column 55: character content of element "file_name" invalid; must be a string matching the regular expression "[^/: ]*" at XPath /package/software_assets/asset/data_file/file_name"

came directly from the `iTunes Transporter`.

**Comment by poscar** [comment]
Oh, I see.  The <file_name></file_name> attribute in the metadata XML file generated for iTunes Transporter does not accept spaces in the name.

Perhaps shenzhen itunesconnect plugin should copy the ipa file into a temporary location with a valid name so that this stage doesn't fail.  Or, just tell the users about valid names in the README.

**Comment by KrauseFx** [comment]
Copying over the file to a temporary folder probably makes sense. I'll update [deliver](https://github.com/KrauseFx/deliver) to do so as well :+1:

**Comment by joemasilotti** [comment]
PR #185 should fix this. It replaces spaces with underscores when saving the ipa.

**Comment by KrauseFx** [comment]
I just noticed, `deliver` already just uses the md5 value of the ipa file name and renames it to `d6c047ca8fbffdf8cc40a379ef959091.ipa` and then stores the file name in the `metadata.xml`. It does the same for screenshots :+1:
