### ISSUE TITLE
fail to publish to pgyer

### ISSUE THREAD

**Issue by shannonchou** [nomad/shenzhen#186]
my command:
ipa distribute:pgyer -f"builds/(Chinese).ipa" -u****** -a***** --trace

/usr/local/lib/ruby/gems/2.1.0/gems/shenzhen-0.10.3/lib/shenzhen/plugins/pgyer.rb:99:in `[]': no implicit conversion of String into Integer (TypeError)
        from /usr/local/lib/ruby/gems/2.1.0/gems/shenzhen-0.10.3/lib/shenzhen/plugins/pgyer.rb:99:in `block (2 levels) in <top (required)>'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/command.rb:155:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/runner.rb:421:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/runner.rb:81:in `run!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/delegates.rb:8:in `run!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.2.0/lib/commander/import.rb:10:in `block in <top (required)>'

**Comment by mattt** [comment]
Fixed by 241ea27.
