### ISSUE TITLE
Appending preprocessors macro fails

### ISSUE THREAD

**Issue by dvkch** [nomad/shenzhen#188]
Hi,

I tried using shenzhen with the following parameter to append preprocessors macro:

    --xcargs GCC_PREPROCESSOR_DEFINITIONS='$(value) DEV_USE_PROD=1'

Unfortunately when the `xcodebuild` command is executed I get the following message

    sh: value: command not found

And in verbose mode I can see the entire parameter is now empty (where it had `DEBUG=0 COCOAPODS=1`)

    Build settings from command line:
        GCC_PREPROCESSOR_DEFINITIONS = 
        SDKROOT = iphoneos8.1

I think when running xcodebuild the dollar sign is not escaped as it should or at least the simple quotes are forgotten

**Comment by dvkch** [comment]
I have been able to workaround:

    --xcargs "GCC_PREPROCESSOR_DEFINITIONS='\$(value) DEV_USE_PROD=1'"

The dollar sign is escaped so the `ipa build` command line doesn't interpret it, and when the parameter is added to xcodebuild I think it becomes 

    GCC_PREPROCESSOR_DEFINITIONS='$(value) DEV_USE_PROD=1'

The single quote prevent sh from interpreting the dollar sign. By adding a build shell script that exports all environment variables to a file I can affirm that my DEV_USE_PROD macro has indeed been **appended**.

**Comment by mattt** [comment]
I'm glad to hear that you found a solution, @dvkch.
