### ISSUE TITLE
if password contains ' or " shenzhen will fail silently

### ISSUE THREAD

**Issue by otusweb** [nomad/shenzhen#189]
Conditions
- password for itunes connect contained a ' and a " 
- password stored in keychain

Command run:
```
$> ipa distribute:itunesconnect -i 00000000 --upload -we -f ./build/xxxxxx.ipa -a xxxx@xxx.com --verbose
Found password in keychain for account: xxxx@xxx.com
/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/bin/iTMSTransporter -m upload -f Package.itmsp -u xxxx@xxx.com -p ''
Upload complete. You may want to double check iTunes Connect to make sure it was received correctly.
```

This only took a few seconds to run. After changing my password to not have those special characters (only letters and numbers) then the app is uploading correctly.

Expected behavior:
command upload file successfully 
or 
give an error asking to change the password to not contain those characters

**Comment by irons** [comment]
This is mostly a bug in iTMSTransporter. I filed http://www.openradar.me/radar?id=5262471291994112 about | and & characters, and the steps to reproduce that bug also work for single and double quotes. 

I'm working on a handful of shenzhen fixes, including better detection of a failure in iTMSTransporter, so at least the ipa tool won't fail silently. Whether shenzhen should include a blacklist of characters in passwords that Apple's tool is currently unable to accept is a separate question.

(Running shellcheck.net on the bash script at `Application Loader.app/Contents/MacOS/itms/share/iTMSTransporter.woa/iTMSTransporter` is scary and enlightening.)

**Comment by mattt** [comment]
Thanks for investigating this, @irons. Since this appears to be an issue with iTMSTransporter, and outside of Shenzhen's control, the best we can do is warn about undesired behavior. 24852ef adds a warning if the password does not match `/0-9a-zA-Z/`; it's harsh, but for lack of a more precise lower bounds of what special characters aren't properly handled, I think this check is warranted.
