### ISSUE TITLE
Add two additional build options

### ISSUE THREAD

**Issue by dvkch** [nomad/shenzhen#190]
Hi,

I currently have issues signing my app, perfectly described by this post: http://stackoverflow.com/a/26548180/1439489

I'm trying to find a solution to the issue and adding those two `build` parameters would really help:

- --xcrunargs: parameters to add to the `xcrun PackageApplication` command. this would allow adding `--preserve-metadata=identifier` for instance
- --verbose: not adding, but extending: output the `xcrun`, `xcodebuild` and other commands, that would help to recall them later instead of rebuilding each time

Thanks for considering!

**Comment by avgx** [comment]
Have you see the solution for  #207 ?

**Comment by mattt** [comment]
Nice suggestions, @dvkch. Verbose logging of `xcrun` and `xcodebuild` are live as of b90d683.

**Comment by dvkch** [comment]
Awesome thanks!
