### ISSUE TITLE
Usernames mangled under verbose logging

### ISSUE THREAD

**Issue by irons** [nomad/shenzhen#193]
One of my iTunes Connect Apple IDs has a plus symbol in it, like bob+favoriteclient@consultant.com. With the verbose flag enabled, shenzhen filters its iTMSTransporter invocation through Shellwords.escape and then through highline (via the ["say" method in Commander] [cmdr]). Shellwords renders the `+` as `\+`, and highline strips it out:

```/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/bin/iTMSTransporter -m upload -f Package.itmsp -u bobfavoriteclient@consultant.com [...]```

It's a cosmetic bug, but when trying to figure out why an iTunes Connect upload is failing, this suggests the email address was modified before being passed along to Transporter, which takes time to disprove. (The actual bug I was looking for was a variant of #189.)

The iTunes Connect password is also subject to transmogrification, but I think the display of the password is a separate problem. We want verbose output in our CI logs, but we'd rather not litter them with working iTunes Connect credentials. I'll have a PR for that shortly.

I'm not sure how to fix the username display. It may be acceptable to just use [`puts` instead of `say`][change], but should the log reflect the username as typed, or the escaped username as executed?

  [cmdr]: https://github.com/tj/commander/blob/a55d5cc7fbf73b73afe76c614c3f6fa467c70e5f/lib/commander/runner.rb#L425
  [change]: https://github.com/nomad/shenzhen/blob/07202cc1c665289af0974c18e34d0c3047f75567/lib/shenzhen/plugins/itunesconnect.rb#L49

**Comment by mattt** [comment]
Good call, @irons. Fixed by c5f18b92155b1f972ca211417be79b77fa3232d7 by replacing with `puts`.
