### ISSUE TITLE
IPA Archive works in bash, fails on Teamcity (the same script, run as the same user)

### ISSUE THREAD

**Issue by turowicz** [nomad/shenzhen#197]
Build log:

http://pastebin.com/raw.php?i=9HRsejBy

Something about derived folder. I've found that -derivedDataPath in xcodebuild can solve that but AFAIK Shenzen doesn't support it.

**Comment by irons** [comment]
Shenzhen can accept arbitrary arguments (with `--xcargs`) or a prefab xcconfig file. Will that suffice?

The build log doesn't appear to include the commands that you're trying to run, either from the ipa tool, or from xcodebuild. If you're still having trouble, it would help to know exactly what commands the script is running, and how the synthesized xcodebuild commands differ under interactive and CI use.

**Comment by mattt** [comment]
Thanks, @irons. Please advise to reopen if this is seen to be a specific issue with Shenzhen itself.
