### ISSUE TITLE
Support for Crashlytics beta distribution groups

### ISSUE THREAD

**Issue by TimPelgrim** [nomad/shenzhen#203]
Crashlytics has added this feature last august. Is this possible with Shenzen or does this need to be added.

**Comment by KrauseFx** [comment]
This is already possible: https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/plugins/crashlytics.rb#L36

**Comment by TimPelgrim** [comment]
My bad, I totally missed this option somehow. Thanks
