### ISSUE TITLE
Wrong signing issue for Release ?

### ISSUE THREAD

**Issue by dornad** [nomad/shenzhen#207]
I'm using the following command to build and sign my IPA with Shenzhen:

*ipa build --scheme MyScheme --configuration Release*

When I check the IPA, the IPA is always built with my Ad-Hoc provisioning profile, which is missing the beta entitlement for the new TestFlight.  

The same project, when built via Xcode 6, is signed correctly.

Any ideas?

**Comment by avgx** [comment]
This solves the issue for me:
```
PROVISIONING_ID="$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< $(security cms -D -i My_release.mobileprovision))"
CODE_SIGN_IDENTITY="iPhone Distribution: Bla-bla-bla, Ltd (XXXXXXXXXX)"
ipa build --verbose -m My_release.mobileprovision -i "${CODE_SIGN_IDENTITY}" --xcargs  PROVISIONING_PROFILE="${PROVISIONING_ID}"
ipa info MyApp.ipa
```

**Comment by TheNathanBlack** [comment]
Any chance we could get that baked into shenzhen?

**Comment by alvaromb** [comment]
I'm having the same issue. Any updates?

**Comment by gantaa** [comment]
@avgx, where do you get that CODE_SIGN_IDENTITY string from?  I took the "common name" from my installed cert and put the User ID from the installed cert in parens, but it is still failing on signing.  I tried to use my valid signing identity with and without the parens.

**Comment by gantaa** [comment]
Actually looks like I have the correct signing identity and provisioning UUID.  The error during signing is "Cannot read resources"

**Comment by gantaa** [comment]
Solved this by setting "Code Signing Resource Rules Path" under my app target's "Build Settings" to: $(SDKROOT)/ResourceRules.plist

Everything now builds correctly with the correct signing cert and profile.  Thanks for the tips @avgx

**Comment by mattt** [comment]
Thanks, @avgx.
