### ISSUE TITLE
Support for Fabric

### ISSUE THREAD

**Issue by deepumukundan** [nomad/shenzhen#209]
Fabric by Crashlytics has one upped their own product by integrating crash reporting and beta distribution into one combined packaged. It would be nice to see support for Fabric added to Shenzen.

**Comment by blebaron** [comment]
I just tried this and it worked for me using the distribute:crashlytics option.

**Comment by avgx** [comment]
If you are using CocoaPods to link with Fabric, you can use such build script to upload and notify your testers:
```
CRASHLYTICS_API_TOKEN="xxxxxxxxxxxxxx"
CRASHLYTICS_BUILD_SECRET="xxxxxxxxxxxxxxxxx"
CRASHLYTICS_FRAMEWORK_PATH=$(pwd)/Pods/Fabric/Crashlytics.framework
CRASHLYTICS_NOTES=$(pwd)/notes.txt
MY_TEST_TEAM=my-mobile-testers

ipa distribute:crashlytics -c ${CRASHLYTICS_FRAMEWORK_PATH} -a ${CRASHLYTICS_API_TOKEN} -s ${CRASHLYTICS_BUILD_SECRET} --notes ${CRASHLYTICS_NOTES} --groups ${MY_TEST_TEAM}
```

**Comment by Rusik** [comment]
Emails option like `ipa distribute:crashlytics ... --email tester1@gmail.com,tester1@gmail.com` is also working
