### ISSUE TITLE
Increased binary size when building with shenzen

### ISSUE THREAD

**Issue by deepumukundan** [nomad/shenzhen#210]
I have a project I am working on and the binary size when built with Xcode build and archive is 18.2MB.
When I build using shenzen I could see that for the same app the ipa file is 21.5MB.
There is a difference of about 3.3MB when building via command line. 
Are there any optimizations I should be setting via command line?

**Comment by mattt** [comment]
Any discrepancy in the size of binaries is likely the result of different build settings, such as those described in [Apple's Technical Q&A 1795](https://developer.apple.com/library/ios/qa/qa1795/_index.html):

> ### Compiler Options
> Setting the Optimization Level build setting to Fastest, Smallest [-Os]; and the Strip Debug Symbols During Copy build setting to Yes (COPY_PHASE_STRIP = YES) can dramatically lower the size of your compiled binary. These settings are the default for the "Release" configuration in Xcode projects.

Shenzhen is not doing anything special; it's only ever delegating to `xcodebuild`. Make sure you are specifying the desired scheme and configuration.
