### ISSUE TITLE
Hockey upload fails to find dSYM.zip file if there is a space in the filename

### ISSUE THREAD

**Issue by egold** [nomad/shenzhen#211]
I have a generated dSYM zip file called 

    ./MyAppName Beta.app.dSYM.zip

(note the space in the name)

However, during Hockey upload I get this error:

    Symbols not found on path /Users/eric/my-apps-directory/MyAppNameBeta.app.dSYM.zip. Crashes won't be symbolicated properly

(note the lack of a space in the error's description of the filename)

The .dSYM.zip gets generated just fine. I checked the datestamp, unzipped the archive, etc. It just has a space in the name, so the Hockey upload of the dSYM fails.

**Comment by egold** [comment]
Looking into the code, it might be that it's inferring the .dSYM.zip filename based on the IPA name passed in, but not using the same IPA name to infer the .dSYM.zip filename. I am specifying an IPA name with no spaces by passing --ipa "MyAppNameSansSpaces.ipa" but the generated dSYM.zip is called "My App Name With Spaces.dSYM.zip"

**Comment by egold** [comment]
This might actually be a fastlane issue. If fastlane sends the correct `options[:dsym_filename]` it ought to work. Tracking the issue in https://github.com/KrauseFx/fastlane/issues/41

**Comment by mattt** [comment]
Looks like KrauseFx/fastlane#41 has been resolved. Please reopen if you are still experiencing issues.
