### ISSUE TITLE
Improve output on build error

### ISSUE THREAD

**Issue by KrauseFx** [nomad/shenzhen#221]
Hey Mattt,

Most issues submitted here are regarding build errors, which are quite often caused by simple code signing issues. The problem I see is the information provided if the build failed. 

Some example outputs when there are code signing issues: 

```
ipa build
```

```
Configuration was not passed, defaulting to Debug
     xcodebuild  ProductHunt.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** ARCHIVE FAILED **
````

Of course, that's not helpful and doesn't provide **any** information about the root of the problem.

When running `--verbose`, the shown information is pretty useless, as `xcodebuild` just fills up the screen.

I piped the output when using `--verbose` into a file. The important bits in case of a code signing error are shown right on the top of the output:

```
=== CLEAN TARGET App OF PROJECT App WITH CONFIGURATION Release ===

Check dependencies
[BEROR]Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “MGTRPU24” were found.
[BEROR]CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.1'
```

@mattt I don't know how you'd approach this solution, but having an output similar to `xctool` or `xcpretty` would be a good first step. I also run into code signing issues for new projects and it's a tedious thing to debug in `shenzhen` right now.

I remember you mentioning, you don't want any dependencies to `xctool` or `xcpretty`, which means, we'd have to roll our own solution.

If you agree, I could prepare a pull request, improving the error handling. This would really improve the quality of this library :+1:

**Comment by shams-ahmed** [comment]
+1

**Comment by KrauseFx** [comment]
Just a small update from my side: `fastlane` now uses `xcpretty` to properly render the `xcodebuild` output and its error messages, with this commit: https://github.com/KrauseFx/fastlane/commit/32c9f37722cc1b008673bd7357f38170dada62ac?w=true

**Comment by KrauseFx** [comment]
Closing in favor of [gym](https://github.com/fastlane/gym)
