### ISSUE TITLE
"ipa build" does not work when SSHing

### ISSUE THREAD

**Issue by jonnyijapan** [nomad/shenzhen#222]
I can build using "ipa build" fine on said computer, but when I ssh into it from another computer it does not work. With verbose logging, the codesign step fails because of user interaction is not allowed-kind of error. This seems to be a problem with xcodebuild. Is there anyway to fix this?

**Comment by mattt** [comment]
All commands can be run in non-interactive mode by specifying all of the required options up front. I can't think of any reasons why SSH would act differently than if the command were issued by, for example, a CI job.

**Comment by KrauseFx** [comment]
@jonnyijapan Maybe this StackOverflow reply helps you: http://stackoverflow.com/questions/25380365/timeout-when-running-xcodebuild-tests-under-xcode-6-via-ssh

**Comment by jonnyijapan** [comment]
The problem, as I found out from another SO q/a was that when using SSH we don't have access to the keychain. Or something similar to that. I don't use SSH to build stuff on a daily basis so this problem does not affect me anyway now.

**Comment by jonnyijapan** [comment]
Here it is. I never tried the suggested answers. Might work or it might not. http://stackoverflow.com/questions/20205162/user-interaction-is-not-allowed-trying-to-sign-an-osx-app-using-codesign
