### ISSUE TITLE
Build performance

### ISSUE THREAD

**Issue by lmirosevic** [nomad/shenzhen#223]
When using shenzhen to do a command line build, for a project of mine it takes about 1:36 to complete the build and create the ipa.

When doing the "same" action in Xcode: clean -> archive, it takes about 0:36.

How come the CLI build takes so much longer? Or am I completely missing something?

**Comment by mattt** [comment]
I can't account for any difference in performance between `xcodebuild` and Xcode Build & Archive.

I'd be happy to review any PRs that improve the overall build speed with Shenzhen, but really the only thing that I'd consider to be a bug, per se, would be if `xcodebuild` on its own was noticeably faster than an equivalent command with Shenzhen.

**Comment by lmirosevic** [comment]
You're right, I should have provided a little more info.

Xcode itself uses `xcodebuild` and `xcrun` under the hood to do the actual compilation/linking/signing/etc so it would be a real shock if those times were different. I did a test and it turns out that it does indeed take the same amount of time to do an archive with `xcodebuild` and using the Xcode GUI, no surprises there.

After some investigating I found something interesting here on [Lines 74-75 inside shenzen/commands/build.rb ](https://github.com/nomad/shenzhen/blob/9a298ed5ff409acf0d227c423704d2fafb68e9ab/lib/shenzhen/commands/build.rb#L74-L75), basically when doing a build with shenzhen like so...
```
ipa build -w "myapp.xcworkspace" -s "myscheme"
```
... it ends up doing a `clean`, then a `build`, then an `archive`.

But an `archive` actually compiles, links, packages, and signs the app. So by adding the `build` step in there as well, it basically compiles/links/etc. the app twice.

Surely that repeat compilation can be avoided?

**Comment by KrauseFx** [comment]
@lmirosevic This pull request will improve the build speed, right? https://github.com/nomad/shenzhen/pull/266/files

**Comment by lmirosevic** [comment]
Yes that will prevent double builds but I believe it will break the rest of the script because there's some "downstream" code that depends on the build artefacts. So I don't think it's that simple.

**Comment by KrauseFx** [comment]
@lmirosevic you might want to add your concerns to https://github.com/nomad/shenzhen/pull/266 :+1:

**Comment by ericlewis** [comment]
@lmirosevic thanks for noting this- i simply wanted to get the discussion started on a PR we could get behind. I'm actually not full sure of the effects of this. So I would love to see if it works or doesn't.

**Comment by Spencevail** [comment]
Same issue here. Seeing a build time of ~1:09:

**From report.xml**
```
 <testcase name="6: ipa" time="4180.888665"/>
```

**Comment by ericlewis** [comment]
@Spencevail can you try building using my PR and seeing what the DIFF is in the filesystem after? its reported that some downstream features need the extra artifacts from the build process- but I'm not entirely sure that is true nor can i really test it fluidly.

**Comment by KrauseFx** [comment]
I just pushed [0.14.4](https://github.com/fastlane/shenzhen/compare/0.14.3...master) on the `shenzhen` fork, which uses this change to speed up builds. Feel free to install it temporary by running `install krausefx-shenzhen`. 

@lmirosevic this issue should be re-opened in my opinion.
