### ISSUE TITLE
[question] Is it possible to use this without a certificate?

### ISSUE THREAD

**Issue by mzarella** [nomad/shenzhen#224]
Hi, I'm completely new to iOS development. I've never used Xcode in my life, I usually am using vim within a linux terminal. Is it possible to build an ipa with shenzhen without a provisioning profile and certificate?

If not, would someone briefly mind telling me how to create these without paying $100. I don't plan on distribute my ipa file through the app store yet, I just want to upload it to my phone so I can see if it works.

**Comment by KrauseFx** [comment]
This is not related to `shenzhen`: you will need a valid certificate to sign the app for installing it on your phone. If you don't want to put it on the AppStore, you could also use an Enterprise Profile, which costs 300$ instead :wink: 

You will not get around using a developer account, to be able to install the app on your iDevice.

**Comment by mattt** [comment]
Thanks, @KrauseFx.
