### ISSUE TITLE
Option to use xctool instead of xcodebuild

### ISSUE THREAD

**Issue by fatuhoku** [nomad/shenzhen#225]
I think that error messages coming out of xctool is much more informative and human-friendly than xcodebuild. What if Shenzhen could check if xctool is on the system, and if it is, use xctool rather than xcodebuild?

**Comment by KrauseFx** [comment]
I also think, error messages are confusing as they are in `shenzhen` right now and created an issue for that: https://github.com/nomad/shenzhen/issues/221

@mattt doesn't want any new dependencies for building the app (see https://github.com/nomad/shenzhen/issues/150 and some other issues).

I haven't played around with it a lot yet, but you can pipe the `--verbose` result from `shenzhen` to `xcpretty`:

```
ipa build --verbose | xcpretty
```

**Comment by mattt** [comment]
.@KrauseFx's advice to pipe into `xcpretty` is what I'd recommend. That, or just use `xctool` or your preferred tool for building, and delegate distribution to Shenzhen.
