### ISSUE TITLE
Upload from URL

### ISSUE THREAD

**Issue by ronbarr** [nomad/shenzhen#226]
I don't know if the API allows this, but if I could integrate my hosted CI provider (Bitrise, I recommend!) life would be good.

**Comment by viktorbenei** [comment]
@ronbarr Shenzen (and the whole nomad-cli) is pre-installed on Bitrise and you can use it through scripts - we even plan to release a Step which uses shenzen, hopefully in the coming weeks ;)

**Comment by mattt** [comment]
Thanks, @viktorbenei.
