### ISSUE TITLE
ipa distribute "notes" argument not recognized

### ISSUE THREAD

**Issue by williamsjj** [nomad/shenzhen#228]
Running ipa 0.13.0

For some reason I can't get ipa to accept the notes on the command line and stop prompting:

`ipa distribute:hockeyapp --token  --notes="yo" --markdown  --release beta   -f 'ipa/file.ipa'  -d 'ipa/file.app.dSYM.zip'`

I always get the editor prompt with the above, rather than using the notes as "yo"

**Comment by mattt** [comment]
What happens if you just use `--notes "yo"` (without `=`)?

**Comment by williamsjj** [comment]
Same result.
```
$ ipa distribute:hockeyapp --token  --notes "yo" --markdown  --release beta   -f 'ipa/file.ipa'  -d 'ipa/file.app.dSYM.zip'
Missing release notes
```

**Comment by williamsjj** [comment]
Figured it out. --token was actually missing it's argument due to a defect in the Makefile.

**Comment by bobgodwinx** [comment]
ipa distribute:hockeyapp -a YourHockeyAppKey --note "$(git log -10)" --markdown --release beta -f 'YourAppName.ipa' -d 'YourAppName.app.dSYM.zip'
