### ISSUE TITLE
IPA path as input for distribute

### ISSUE THREAD

**Issue by viktorbenei** [nomad/shenzhen#229]
Would be fantastic if the IPA's path could be specified as an input for `ipa distribute`, in case it's not in the current working dir.

**Comment by mattt** [comment]
All distribution methods support the `-f` flag to do exactly that.

**Comment by viktorbenei** [comment]
@matt thanks, it's not mentioned in the README at all, that's why I thought there's no option for this

**Comment by maridansoft** [comment]
does this mean that I can say do

ipa distribute:itunesconnect -a me@email.com -p myitunesconnectpassword -i appleid --upload -f blabla.ipa          and ipa would be uploaded???

**Comment by viktorbenei** [comment]
@maridansoft yes, we do exactly that - you can find our build step which does exactly that here: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-shenzhen/blob/master/step.sh

**Comment by maridansoft** [comment]
cool! any way instead of appId use bundleidenitifier?
