### ISSUE TITLE
Changing build to use xcodebuild archive/exportArchive new actions

### ISSUE THREAD

**Issue by maschall** [nomad/shenzhen#232]
In the Xcode 6.0, Apple updated xcodebuild to expose a new action called exportArchive, that can take an archive file and create an ipa file.  Would this be a more desired approach than using the PackageApplication script (as much as I'm 99% sure that exportArchive just calls PackageApplication internally)?  I wasn't sure about the policies for Xcode backwards compatibility for this project.

**Comment by mattt** [comment]
For the time being, I think it makes sense to take an "if it ain't broke..."-approach. Should Xcode's documentation or Apple's recommendations change to explicitly use this new approach, that's when it would be appropriate to update.

**Comment by eholzwarth** [comment]
This is now broke, so... can we fix it? Relevant links:
Recommended solution: http://stackoverflow.com/questions/32763288/ios-builds-ipa-creation-no-longer-works-from-the-command-line

Temporary workaround: http://stackoverflow.com/a/26674605
