### ISSUE TITLE
Add parameter to specify DSYM output filename

### ISSUE THREAD

**Issue by djkitsch** [nomad/shenzhen#234]
It'd be tremendously useful to be able to customise the output DSYM ZIP filename, as tools like Crittercism don't play well with escaped filenames.

(Otherwise awesome tool - keep it up!)

**Comment by mattt** [comment]
Just wondering, is there anything this would accomplish that `mv` could not?

**Comment by djkitsch** [comment]
That's actually what my build and distro script's doing right now, but since the generated DSYM file is named automatically, if you do use `--ipa`, the names of the IPA and DSYM output files no longer match. It's by no means a critical bug, just a suggestion for consistency and simpler build scripts with fewer moving parts (pardon the pun!).

**Comment by mattt** [comment]
I'd prefer to minimize the functional surface area of the tool as much as possible, preferring composability over customizability. To that end, I'd recommend continuing to use `mv` for this.
