### ISSUE TITLE
Build and sign failing

### ISSUE THREAD

**Issue by CraigSiemens** [nomad/shenzhen#236]
When building my app and passing the certificate and provisioning profile, it fails with the following error.

```
error: /usr/bin/codesign --force --preserve-metadata=identifier,entitlements,resource-rules --sign CERT_NAME --resource-rules=/var/folders/20/0kqxp2dx2n90121zr32rbjh00000gn/T/8NLTsWSWCj/Payload/example.app/ResourceRules.plist --entitlements /var/folders/20/0kqxp2dx2n90121zr32rbjh00000gn/T/8NLTsWSWCj/entitlements_plistQWez0eVt /var/folders/20/0kqxp2dx2n90121zr32rbjh00000gn/T/8NLTsWSWCj/Payload/example.app failed with error 1. Output: Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
Warning: --resource-rules has been deprecated in Mac OS X >= 10.10!
/var/folders/20/0kqxp2dx2n90121zr32rbjh00000gn/T/8NLTsWSWCj/Payload/example.app/ResourceRules.plist: cannot read resources
```

Since `codesign` is called by `xcrun -sdk iphoneos PackageApplication...` it might not be easy to fix.

Any suggestions or workarounds?

**Comment by ashfurrow** [comment]
I'm getting the same error. The app at `/var/folders/whatever` _does_ exist, but it has no `ResourceRules.plist` file. Any suggestions?

**Comment by ashfurrow** [comment]
Managed to get it apparently working for me. Following some advice from [this SO question](http://stackoverflow.com/questions/26516442/how-do-we-manually-fix-resourcerules-plist-cannot-read-resources-error-after), I added a value of `$(SDKROOT)/ResourceRules.plist` for the `CODE_SIGN_RESOURCE_RULES_PATH` value in by build settings. 

![screen shot 2015-04-01 at 9 47 45 pm](https://cloud.githubusercontent.com/assets/498212/6956278/6d3fd06e-d8b9-11e4-8a42-a23ff85c70f1.png)

Then it seemed to work ¯\_(ツ)_/¯

**Comment by mattt** [comment]
Thanks for sharing your workaround, @ashfurrow. If there's anything you think that Shenzhen could do differently to mitigate this issue, please open a new issue or PR.
