### ISSUE TITLE
Problem with sign and identity

### ISSUE THREAD

**Issue by RobertNNms** [nomad/shenzhen#247]
Hi,

Actually, I use this command:

ipa build -clean -p myProject.xcodeproj -c AdHoc -s myProject --xcconfig $xcconfig.xcconfig -m $provision.mobileprovision -i "$identity"
and I obtain the following error:
--------------------
Output:
xcodebuild  myProject.xcodeproj
/var/folders/ls/n_kz5z3503dg7dz3g41_vl240000gn/T/SchemeScriptAction-Sbh4wg: line 7: syntax error near unexpected token `newline'
/var/folders/ls/n_kz5z3503dg7dz3g41_vl240000gn/T/SchemeScriptAction-Sbh4wg: line 7: `API_TOKEN=<269413d5-43bf-45db-b40a-0b154fbf5f7b>'
          xcrun  PackageApplication
error: /usr/bin/codesign --force --preserve-metadata=identifier,entitlements,resource-rules --sign iPhone Distribution: xxxxxxx --resource-rules=/var/folders/ls/n_kz5z3503dg7dz3g41_vl240000gn/T/Pzc5QvEe1H/Payload/myProject.app/ResourceRules.plist --entitlements /var/folders/ls/n_kz5z3503dg7dz3g41_vl240000gn/T/Pzc5QvEe1H/entitlements_plistp5YjsoF7 /var/folders/ls/n_kz5z3503dg7dz3g41_vl240000gn/T/Pzc5QvEe1H/Payload/myProject.app failed with error 1. Output: Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
Warning: --resource-rules has been deprecated in Mac OS X >= 10.10!
/var/folders/ls/n_kz5z3503dg7dz3g41_vl240000gn/T/Pzc5QvEe1H/Payload/myProject.app/ResourceRules.plist: cannot read resources
-------------------

An idea, how to solve the problem?

Thanks

**Comment by mattt** [comment]
You have a script that runs as part of your build phase that has errors. This is not an issue with Shenzhen.
