### ISSUE TITLE
Shenzhen - Crash when trying to download provisioning profiles

### ISSUE THREAD

**Issue by kentpickard** [nomad/shenzhen#248]
Sorry - posted in wrong github project

Command I'm trying to run:

ios profiles:download:all --type development  -u #{USER} -p #{PASSWORD} --trace

/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/agent.rb:210:in `list_profiles': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:421:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/import.rb:10:in `block in <top (required)>'

**Comment by mattt** [comment]
This is Shenzhen. You seem to be asking about Cupertino.
