### ISSUE TITLE
xcode has to be opened once

### ISSUE THREAD

**Issue by sneps85** [nomad/shenzhen#252]
hello,

i am using jenkins with an mac os x node to build my apps automatically. unfortunately, an app has to be opened once in xcode on the node to get "ipa build" working, as i do not have the user-specific xcode properties in the git repository.

or what am i doing wrong?

**Comment by aenglund** [comment]
What kind of error message do you get? Do you rely on the properties set in the xcode project?
Do you attempt to unlock your keychain so that xcodebuild can access your signing certificates etc before running the `ipa build`-command?

**Comment by mattt** [comment]
@sneps85 That sounds right, yeah. Shenzhen requires `xcodebuild` to be able to be run successfully, for which having and launching Xcode is a prerequisite.
