### ISSUE TITLE
Invalid WatchKit Support

### ISSUE THREAD

**Issue by AnYuan** [nomad/shenzhen#254]
Hi, great tool !

I have one problem when uploading ipa to iTunes Connect:
Invalid WatchKit Support - The bundle contains an invalid implementation of WatchKit. The app may have been built or signed with non-compliant or pre-release tools.

I think it is because of the format of the ipa file.

could you please help me.
Thanks a lot

**Comment by hjanuschka** [comment]
same issue here - if building via xcode and submiting via xcode it works
if building via `ipa` it compplains about invalid binary

any news on that?

**Comment by JaiKumarB** [comment]
Same here. Any updates?

**Comment by JaiKumarB** [comment]
This PR seems to solve the issue https://github.com/nomad/shenzhen/pull/258

**Comment by mattt** [comment]
Fixed by #258.

**Comment by AnYuan** [comment]
Thanks！
