### ISSUE TITLE
SSL verification fails

### ISSUE THREAD

**Issue by angrauel** [nomad/shenzhen#255]
`ipa distribute:hockeyapp -a xxx -i xxx -r alpha -f xxx.ipa -d xxx.app.dSYM.zip -m "" --notify --verbose --trace`

I get the following error message: 

> http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Does anybody has the same problem? I'm on latest Yosemite and use ruby 2.2.0 installed with homebrew.

**Comment by gbasile** [comment]
same problem here

**Comment by mattt** [comment]
This most likely indicates that HockeyApp's API is not serving valid SSL certificates. You should contact their support to get this resolved.

**Comment by samdods** [comment]
hi @mattt - is this possible even though the upload is successful using the HockeyApp API directly from the command line using `curl` and `https`? doesn't that suggest that their API is working fine?

**Comment by drubin** [comment]
The bug is in fact not related to either `shenzen` or hockey app's SSL certs.  But posting this here to help others having the same issue.

## Fix 
From https://github.com/Homebrew/homebrew/issues/32251#issuecomment-71938608
Removing the expired certificate fixes it

     sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338/System/Library/Keychains/SystemRootCertificates.keychain
     brew postinstall openssl

### Some debugging steps

Test with [ssl-doctor](https://github.com/mislav/ssl-tools)

Before 

    ruby doctor.rb upload.hockeyapp.net:443
    OpenSSL 1.0.1i 6 Aug 2014: /usr/local/etc/openssl
    SSL_CERT_DIR=""
    SSL_CERT_FILE=""

    HEAD https://upload.hockeyapp.net:443
    OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

    The server presented a certificate that could not be verified:
      subject: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
      issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
      error code 10: certificate has expired 

Fix 

     sudo security delete-certificate -Z2F173F7DE99667AFA57AF80AA2D1B12FAC830338/System/Library/Keychains/SystemRootCertificates.keychain
     brew postinstall openssl

Verify 

    ruby doctor.rb upload.hockeyapp.net:443
    OpenSSL 1.0.1i 6 Aug 2014: /usr/local/etc/openssl
    SSL_CERT_DIR=""
    SSL_CERT_FILE=""
    HEAD https://upload.hockeyapp.net:443
    OK

**Comment by raggi** [comment]
https://github.com/raggi/openssl-osx-ca
