### ISSUE TITLE
Upgrade from 0.13.1 to 0.14 - ipa won't execute after upgrade

### ISSUE THREAD

**Issue by matthewchartier** [nomad/shenzhen#257]
I have been successfully using previous versions of the tool, but when I upgrade to 0.14, the ipa tool won't run. I get:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'highline (>= 1.7.1)', already activated 'highline-1.6.11' (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/bin/ipa:22:in `<main>'

If I uninstall highline-1.6.11 and try I get:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'highline' (~> 1.6.11) - did find: [highline-1.7.2,highline-1.7.1] (Gem::LoadError)

I'm sure I doing something wrong... any thoughts?

**Comment by truth3** [comment]
Hey Matthew, there is another post on fastlane that addresses this problem (link below) but this did not work for me. I uninstalled fastlane and all dependents along with shenzhen and then installed it all again and it resolved my problems.

https://github.com/KrauseFx/fastlane/issues/194

Hope that helps

**Comment by matthewchartier** [comment]
Didn't solve it for me...

**Comment by truth3** [comment]
Hey Matthew, what specific gems did you uninstall? I can try and run through my history this afternoon to show you what I removed

**Comment by matthewchartier** [comment]
I uninstalled fastlane, highline (all versions) and shenzhen (all versions). Then installed shenzhen, which installed highline-1.7.(1 or 2). It completed successfully. When I run ipa, it says:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'highline' (~> 1.6.11) - did find: highline-1.7.2,highline-1.7.1

If I then install highland-1.6.11, I get: can't satisfy 'highline (>= 1.7.1)', already activated 'highline-1.6.11' (Gem::LoadError)

Thanks for your help!

**Comment by JaviLorbada** [comment]
Hi @matthewchartier, I had the same issue, I solved it by updating commander.

I tried first to uninstall highline, and I saw commander-4.3.0 depends on highline (~> 1.6.11), so I did update commander `gem update commander` to version 4.3.3.

As you can see [here](https://rubygems.org/gems/commander), now commander it depends on highline 1.7.2.

So no I have no problems using shenzen nor fastlane, hope that solves your issue as well 🙏

**Comment by truth3** [comment]
Hey Matthew, just looked at my history.. and this is what I have (please keep in mind this is all new territory for me.. and I am sure there is a cleaner way to resolve this)

Uninstall:
nokogiri
cupertino
deliver
fastlane

Install:
nokogiri --use system-libraries
fastlane
nomad-cli

Update: 
Cupertino
fastlane_core
commander

**Comment by truth3** [comment]
Nice Javi.. I was wondering if commander was they key, and it looks like you confirmed that :)

**Comment by matthewchartier** [comment]
Confirmed. Update command and it fixed it. Thanks Javi and truth3, appreciate the help.

**Comment by nonstriater** [comment]
" gem update commander " solve my problem

**Comment by ariguererro** [comment]
this solve!

**Comment by chrisbirch** [comment]
@JaviLorbada Nice one. Works for me
