### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kilabyte** [nomad/shenzhen#259]
When i try to do just "ipa build" it gives me an error of "Check Dependancies". The project builds fine with Xcode.

**Comment by truth3** [comment]
Hey Kilabyte, if you run with --verbose at the end of the command you will get more insight into the error. Could be the build service can't access your keychain

**Comment by kilabyte** [comment]
"Build Failed The following build commands failed: Check dependencies, (1 failure) archive failed"

**Comment by truth3** [comment]
Do you have many projects within that folder where you run the command?

**Comment by kilabyte** [comment]
nope this is the only project in that folder. no workspace just simple project. The project does have 2 other target dependencies (libraries) but when it asks i select the Xcode project file

**Comment by aenglund** [comment]
I've got that error when provisioning profile can't be automatically resolved for the target's bundle identifier. Maybe that is the case for you as well?

**Comment by kilabyte** [comment]
I only have one provisioning profile installed to my machine and it is setup within the Xcode build settings to use that profile. is there a parameter that i should be specifying at the command line?

**Comment by aenglund** [comment]
You only need to specify it via the command line if you want to override what is defined in your xcode project. My tip is to build your app with the same build configuration as you use with the `ipa`-command and export it as an IPA through xcode. You will probably get a more explanatory error description there.. My guess is that you have an issue with your provisioning profile.

**Comment by kilabyte** [comment]
i can't do that. At work i don't have access to the dev portal to give myself the adhoc cert (i know i should) so iv just been archiving and then importing into iTunes to create the IPA but its just a pain. so when i saw this tool i thought great! i can do it from the command line super quick. guess not.

**Comment by mattt** [comment]
This appears to be an issue related to particular project configuration and `xcodebuild` rather than anything to do with Shenzhen itself. You may continue your discussion, but I'm going to close this issue.
