### ISSUE TITLE
Uploading to iTunesConnect fails with Xcode 6.3.1

### ISSUE THREAD

**Issue by GeorgeSealy** [nomad/shenzhen#262]
I've had trouble with the command: 

ipa distribute:itunesconnect

failing quietly. It appears that for the version of Xcode I'm using (6.3.1) the path to the iTMSTransporter executable has changed to:

/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/MacOS/itms/bin/iTMSTransporter

from:

/Applications/Xcode.app/Contents/Applications/ApplicationLoader.app/Contents/MacOS/itms/bin/iTMSTransporter

Running iTMSTransporter manually worked as expected, but ipa fails.

Happy to add more information here as needed.

**Comment by KrauseFx** [comment]
Are you using the latest version of `shenzhen`? This should be fixed with https://github.com/nomad/shenzhen/commit/837306e3babc8dbf8fa2b45ea20b23f271227540

**Comment by GeorgeSealy** [comment]
Looks like the gem update for nomad-cli didn't work the first time round, updated shenzhen specifically, and it's up to date now. Thanks for the help.

**Comment by KrauseFx** [comment]
Glad I could help :+1:
