### ISSUE TITLE
** ARCHIVE FAILED ** in red color after build 

### ISSUE THREAD

**Issue by AliAyasrah** [nomad/shenzhen#272]
hello

i am trying to create api file, but i always getting an error, this is what i did : 
$ cd to my project, than $ ipa build

i got this : 
xcodebuild Watch.xcodeproj
** BUILD FAILED **
The following build commands failed:
Check dependencies
(1 failure)
** ARCHIVE FAILED **

when i tried this line $ ipa build --embed "iOS Team Provisioning Profile" --verbose

after build i got this ** ARACHIVE FAILED ** in red color without error message

i have no idea please help

thanks

**Comment by KrauseFx** [comment]
@AliAyasrah Try running `shenzhen` in `verbose` mode: `ipa build --verbose`. To make the output clearer it's a good idea to pipe it to `xcpretty`: `ipa build --verbose | xcpretty`.

**Comment by AliAyasrah** [comment]
thank you for replay 

i got very long text i searched about error word : 

[BEROR]Code Sign error: Provisioning profile does not match bundle identifier: The provisioning profile specified in your build settings (“iOSTeam Provisioning Profile: com.comName.Watch”) has an AppID of “com.comName.Watch” which does not match your bundle identifier “com.comName.WatchTests”.
		[BEROR]CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.3'

please can you tell me what should i do ?

**Comment by KrauseFx** [comment]
You seem to building the tests as well, which shouldn't be the case for Release builds. You'll have to go through your Xcode project settings.

**Comment by AliAyasrah** [comment]
@KrauseFx 
i went to :
http://stackoverflow.com/questions/26109851/code-signing-is-required-for-product-type-unit-test-bundle-in-sdk-ios-8-0

after that i got 
Successfully built:


and its work fine 
thank you

**Comment by KrauseFx** [comment]
Great to hear :+1:
