### ISSUE TITLE
ipa distribute:s3 not working

### ISSUE THREAD

**Issue by goleador** [nomad/shenzhen#274]
I am getting this puzzling error message:

Error while uploading to S3: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

Credentials have been checked and I am able to upload files using the same credentials.

**Comment by leonsas** [comment]
+1

**Comment by thomasjoulin** [comment]
I've had the same issue, when my bucket name is a virtual host ("subdomain.domain.com")
