### ISSUE TITLE
No matching provisioning profile found

### ISSUE THREAD

**Issue by AliAyasrah** [nomad/shenzhen#275]
hello 
i am trying to build(apple watch project) by Jenkins 
this what i call 
$ cd to workplace 
[code] $/usr/bin/ipa build -s "WatchName" -m "~/Library/MobileDevice/Provisioning\ Profiles/94XXXXXXXXXX78d.mobileprovision" -i 'iPhone Distribution: companyname (CXXXXXX) --verbose --clean [/code]

and i got these : 
Code Sign error: No matching provisioning profile found: Your build settings specify a provisioning profile with the UUID “94XXXXXXXXXX78d”, however, no such provisioning profile was found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.3'

please help

**Comment by mattt** [comment]
That sounds pretty self-explanatory. Your provisioning profile is not at the specified path. 

Since this isn't really an issue with Shenzhen, I'm going to close this issue.
