### ISSUE TITLE
Install ipa to device

### ISSUE THREAD

**Issue by cybertk** [nomad/shenzhen#280]
I know there are some tools used to upload .ipa to device, such as [fruitstrap](https://github.com/ghughes/fruitstrap), [ios-deploy](https://github.com/phonegap/ios-deploy) and [libimobiledevice](https://github.com/benvium/libimobiledevice-macosx). But I am thinking it's better if **shenzhen** can also provide this feature. Then we can keep tools used in project minimal and consistent.

**Comment by bleonard** [comment]
+1

**Comment by RobinChao** [comment]
+1
