### ISSUE TITLE
Proxy value for code signing identity to both xcodebuild and xcrun

### ISSUE THREAD

**Issue by andyvb** [nomad/shenzhen#281]
Right now, if you override the value of the code signing identity via the `ipa build` command, you need to set the identity in two command lines args:

`--identity "my identity"` and `--xcargs "CODE_SIGN_IDENTITY='my identity"`

This is non-obvious, unless you're already super familiar with the usage of `xcodebuild` and `xcrun`, and you also know that Shenzhen uses both of these tool internally.  Shenzhen should pass in the value of `--identity` to `--xcargs` for you automatically.

If you don't do this, during upload to Apple's TestFlight validation will fail due to mismatched code signing identities for compilation vs packaging the IPA.

```
ipa build --clean --verbose --sdk iphoneos --scheme MyApp --workspace MyApp.xcworkspace --configuration Release --embed "my_app.mobileprovision" --identity "iPhone Distribution: My Company" --xcargs "CODE_SIGN_IDENTITY='iPhone Distribution: My Company'"
```

**Comment by KrauseFx** [comment]
Thanks for the information @andyvb. That helps a lot, I'll take a closer look later today :+1:
