### ISSUE TITLE
undefined method `say_error'

### ISSUE THREAD

**Issue by Khronoss** [nomad/shenzhen#282]
Hi,
I'm using the Crashlytics action in the Fastlane tools chain to upload my app on Crashlytics. I use a distant server to automate the build/upload phases with Jenkins.
The issue is that the job fails when starting Crashlytics and print out this error : 

/Library/Ruby/Gems/2.0.0/gems/krausefx-shenzhen-0.14.3/lib/shenzhen/plugins/crashlytics.rb:11:in `initialize': undefined method `say_error' for #<Shenzhen::Plugins::Crashlytics::Client:0x007f8c369d93c8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/actions/crashlytics.rb:34:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/actions/crashlytics.rb:34:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):79:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:39:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:39:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:29:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:29:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/bin/fastlane:128:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/bin/fastlane:134:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

I also add @KrauseFx to be notified on that issue because I don't have enough skills in Ruby to know if it comes from the Fastlane tool chain or from your Shenzhen library

**Comment by KrauseFx** [comment]
Sorry, that's an issue of `fastlane`, could you submit the issue over there to discuss it further?

**Comment by Khronoss** [comment]
Done :) Here is the link to it https://github.com/KrauseFx/fastlane/issues/383

Thanks \o

**Comment by KrauseFx** [comment]
You can close this issue here now :+1:
