### ISSUE TITLE
Is there a way to not include the DSYM when creating ipa from the command line for S3?

### ISSUE THREAD

**Issue by awadhawan** [nomad/shenzhen#286]
So, I'm using this amazing ibrary (Thank you so much for it) to create an ipa from the command line and upload it to S3. 
I'm using <code>distribute:s3 -a ACCESS_KEY_ID -s SECRET_ACCESS_KEY -b BUCKET</code> for it. I tried looking for it but can't seem to find a command to not include the DSYM when uploading. Does Shenzhen support this behavior?
Thanks!

**Comment by jWolo** [comment]
Did you ever get this question answered? I'm using Unity to create my xcode projects and when we have Dwarf + DSYM our builds take considerably longer to perform than when just using DWARF. And we have determined DSYM is just not worth the extra time. I also couldn't find anything in the documentation about disabling it.

**Comment by ecommerceappbook** [comment]
You can disable it in Xcode project setting.

Liangjun Jiang


Download our mobile apps at App Store 
https://itunes.apple.com/us/app/buy-from-farm/id970844848?mt=8

and Google Play Sore
https://play.google.com/store/apps/details?id=com.ljapps.farmersmarket

**Comment by jWolo** [comment]
Right I know that but when I have it disabled this error occurs when using Shenzen
```
jwolo@Mac-mini ~/projetpath> ipa build
Configuration was not passed, defaulting to Debug
     xcodebuild  Unity-iPhone.xcodeproj
          xcrun  PackageApplication
            zip  /projectpath.app.dSYM
cp: /projectpath.app.dSYM: No such file or directory
```

**Comment by ecommerceappbook** [comment]
For debug and installing on simulator, we can disable the dsym. For build purpose, probably we can't. 

Liangjun Jiang

Download our mobile apps at App Store 
https://itunes.apple.com/us/app/buy-from-farm/id970844848?mt=8

and Google Play Sore
https://play.google.com/store/apps/details?id=com.ljapps.farmersmarket
