### ISSUE TITLE
how to build an enterprise release

### ISSUE THREAD

**Issue by taocore** [nomad/shenzhen#290]
use the default "ipa build", I always get an output with "ProvisionedDevices" with limit devices instead of ProvisionsAllDevices        | true

**Comment by taocore** [comment]
use -m distribution.mobileprovision option get the same result

**Comment by dongyuan** [comment]
We had the same problem -m doesn't work.
Cheers

**Comment by KrauseFx** [comment]
The best and easiest way is to set the code signing settings in your Xcode project. I published a [Code Signing Guide](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) that shows you how to do code signing with `shenzhen`.
