### ISSUE TITLE
TestFlight Beta Testing set to default on

### ISSUE THREAD

**Issue by moses-gangipogu** [nomad/shenzhen#294]
after uploading the .ipa to itunes connect i have to manually go and toggle "TestFlight Beta Testing" to make it active,
any way by which i can automate this last step also

**Comment by truth3** [comment]
Did you pass in the beta parameter and set it to True on the deliver step?

**Comment by KrauseFx** [comment]
`shenzhen` does not submit the app for beta testers, but only uploads the binary. You can use [pilot](https://github.com/fastlane/pilot) or [deliver](https://github.com/fastlane/deliver) for it :rocket:

**Comment by truth3** [comment]
Nice call Felix... I totally forgot this wasn't fastlane thread :)

**Comment by moses-gangipogu** [comment]
:+1:
