### ISSUE TITLE
OS X El Capitan, ipa not added to path?

### ISSUE THREAD

**Issue by jonnyijapan** [nomad/shenzhen#297]
I'm not sure what happened, but after updating to El Capitan GM seed, ipa was gone.
So I reinstalled it with sudo.
However, my jenkins job complained that it couldn't find ipa. Double checked that the jenkins job ran as me (my user)... still no ipa. I now run ipa with the absolue path in jenkins, it seems to be fine. Still not sure why the shorthand command no longer works in Jenkins...

Btw, ipa IS added to path, because it works when tapping it into Terminal. I guess Jenkins runs things different.

**Comment by hjeffrey** [comment]
I guess Ei Captain limited something.
These commands make it working:
`gem install shenzhen --user-install -n~/bin`
`echo "gem: --user-install -n~/bin" >> ~/.gemrc`

**Comment by mribeiro** [comment]
Hey @hjeffrey 

I can confirm this works quite well, just need to add my user's bin folder to PATH.
I'm no gem expert, could you please explain what those commands actually do?
Thank you

**Comment by orkenstein** [comment]
Does not help to me.

**Comment by orkenstein** [comment]
Getting this:
```
gem install shenzhen --user-install -n~/bin

**Comment by shpasta** [comment]
@hjeffrey after your comands I received this result;
`  
WARNING:  You don't have /Users/username/bin in your PATH,
	  gem executables will not run.
Successfully installed shenzhen-0.14.2
Parsing documentation for shenzhen-0.14.2
1 gem installed
`  
Setup username in my PATH variable, repeated install commands but still receiving this error, and ipa is not working
