### ISSUE TITLE
ipa distribute:itunesconnect fails with ERROR ITMS-90161 on MacOSX

### ISSUE THREAD

**Issue by mgrilloteravisiongames** [nomad/shenzhen#298]
Hi all!, I've been using shenzhen 0.14.2 on OSX 10.10.2 Yosemite, I have XCode 6.2. Everytime I try to upload an ipa from command line it fails the following way:

    security: SecKeychainItemCreateFromContent (<default>): The specified item already exists in the keychain.
    /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/bin/iTMSTransporter -m upload -f Package.itmsp -u <USERNAME> -p ******

    Package Summary:

    1 package(s) were not uploaded because they had problems:
        <DIR>/Package.itmsp - Error Messages:
                ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.testing.test [Payload/test.app] is invalid.
                [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

If I use the organizer on the same ipa, the upload is successfull. The build was done using:

    $ ipa build -m <PRODUCTION PROVISIONING FILE>

Do you have any idea why this might be happening?

Best Regards,

**Comment by kevinstueber** [comment]
@mgrilloteravisiongames FWIW, I'm experiencing the same situation. Were you able to make any progress on the issue?

**Comment by mgrilloteravisiongames** [comment]
Nope, I started playing with gym from fastlane: https://github.com/fastlane/gym

**Comment by kevinstueber** [comment]
Thanks for the tip, works for me :)

**Comment by pesterhazy** [comment]
I'm seeing the same problem: Invalid Provisioning Profile
