### ISSUE TITLE
Resource rules problem with XCode 7.0

### ISSUE THREAD

**Issue by yamanyar** [nomad/shenzhen#299]
Hi,

Adding "$(SDKROOT)/ResourceRules.plist for the CODE_SIGN_RESOURCE_RULES_PATH" is not a solution for XCode 7.0. If you do not add this property following problem occurs: https://github.com/nomad/shenzhen/issues/277 

With XCode 7.0:

Resource Rules

Systems before OS X Mavericks v10.9 documented a signing feature (--resource-rules) to control which files in a bundle should be sealed by a code signature. This feature has been obsoleted for Mavericks. Code signatures made in Mavericks and later always seal all files in a bundle; there is no need to specify this explicitly any more. This also means that the Code Signing Resource Rules Path build setting in Xcode should no longer be used and should be left blank.

It is thus no longer possible to exclude parts of a bundle from the signature. Bundles should be treated as read-only once they have been signed.

**Comment by akashivskyy** [comment]
Bumping this, I have the same issue.

**Comment by avgx** [comment]
http://stackoverflow.com/a/26674605/2060780 solves it for me.

**Comment by akashivskyy** [comment]
As I didn't want to modify Xcode bundle, I just removed `-i` (`--identity`) argument from my `ipa` invocation. Seems to be working.

**Comment by avgx** [comment]
@akashivskyy thank's, your solution works and is better.
