### ISSUE TITLE
ipa distribute:crashlytics no more notifications?

### ISSUE THREAD

**Issue by jonnyijapan** [nomad/shenzhen#300]
Sending builds to crashlytics no more produces notification emails to testers. The builds end up on crashlytics/fabric fine but no emails are sent out.

I notice an option for this command: "-n, --notifications [YES | NO] Should send notification email to testers? "
I have not used it before, but emails have previously been sent out fine.
I tried this option (both -n YES and --notifications YES", but no emails are still sent out.

FWIV, this issue appeared happened after going to OS X El Capitan from the previous OS X.

I have no idea where the error is; maybe the API of Fabric changed/stopped working.

Update: i believe the problem is with Fabric/Crashlytics. Even using the "native" way of the framework to upload builds, no emails are sent out. https://docs.fabric.io/ios/beta/build-tools.html If someone can confirm that please feel free to close this issue. It still remains a problem though cause I have to send emails manually. .Doh.

**Comment by Akhrameev** [comment]
I use Yosemite on build server and El Capitano for development. Both works fine and sends emails (I've added "-n YES"). I've sent email to just one target via "-e <my_email>", than changed command to use groups (I hate long CSVs with emails) via "-g <group_alias>".
