### ISSUE TITLE
error : build watchos2 by Xcode 7.0

### ISSUE THREAD

**Issue by AliAyasrah** [nomad/shenzhen#302]
I am trying to build watchkit os2 but i got this error :
"target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphonesimulator' platform" 

I tried may way but no chance to solve it, please help : 

Screenshot:
 'http://s12.postimg.org/ou01lxva5/Screen_Shot_2015_09_29_at_13_04_38.png'

**Comment by salabaha** [comment]
Have the same issue

**Comment by AliAyasrah** [comment]
@salabaha 
yes

this to replaced with this tool  
https://github.com/fastlane/gym

**Comment by salabaha** [comment]
Thanks, used it already. Work just fine.
