### ISSUE TITLE
s3 distrubution - RuntimeError

### ISSUE THREAD

**Issue by lsolniczek** [nomad/shenzhen#305]
I use s3 action to distribute my app, but I get strange error:

`error: uninitialized constant Shenzhen::Plugins::S3::Client::AWS`

It is strange, because just before a fastlane update it worked. .Have anybody have idea how to fix this?

**Comment by truth3** [comment]
@lsolniczek Do you have this in your gem list `krausefx-shenzhen` ?

**Comment by lsolniczek** [comment]
Yes, I have installed gem `krausefx-shenzhen`.

I've just done test. I've remove `krausefx-shenzhen -v 0.14.6` and install `krausefx-shenzhen -v 0.14.5` and it starts work. It looks like there is some problem with `krausefx-shenzhen -v 0.14.6`

**Comment by Damien-B** [comment]
@lsolniczek I get the same problem, so I tried to change ```krausefx-shenzhen``` to v0.14.5 but I get this issue when trying to start s3 action :
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'krausefx-shenzhen' (>= 0.14.6) - did find: [krausefx-shenzhen-0.14.5] (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/bin/fastlane:22:in `<main>'
```
...which I don't really get
How did you manage to make that work ?
