### ISSUE TITLE
ipa build with --sdk appletvos fails `xcrun` step

### ISSUE THREAD

**Issue by themartorana** [nomad/shenzhen#312]
Hi.

I'm trying to use this to automate AppleTV builds, and it's almost there. As long as you pass `ipa build --sdk appletvos ...` the `xcodebuild` step works beautifully.

However, the `xcrun` state fails.

```
$ xcrun -sdk appletvos PackageApplication -v "..." -o "..." --embed "..."  --verbose

** ARCHIVE SUCCEEDED **

          xcrun  PackageApplication
xcrun -sdk appletvos PackageApplication -v "....app" -o "....ipa" --embed "..."  --verbose

xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
```

However, if I copy the command-line argument and replace `-sdk` to `xcrun` with `iphoneos` it packages the IPA properly. I was hinted towards that by this in the tvOS Developer Library:

```
Note: tvOS binaries are also iOS App files with an .ipa filename extension.
```

https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/TestingYouriOSApp/TestingYouriOSApp.html#//apple_ref/doc/uid/TP40012582-CH8-SW17

I'm not sure what an appropriate solution to this is, since you need to pass a different `--sdk` argument to `xcodebuild` and `xcrun`.

Thanks!

Dave

**Comment by markj** [comment]
Davae, did you get anywhere with this? 

Stuck with the same problem.

**Comment by themartorana** [comment]
Mark - unfortunately not. I ended up using the native Xcode tools.

**Comment by HaloWang** [comment]
Same problem

**Comment by pbassut** [comment]
Same issue
