### ISSUE TITLE
While executing gem ... (Errno::EPERM)     Operation not permitted - /usr/bin/aws-rb

### ISSUE THREAD

**Issue by jffun** [nomad/shenzhen#316]
First, I use "gem install shenzhen" command to get shenzhen, got a error"You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory";
So, I use "sudo gem install shenzhen",still got an error"Operation not permitted - /usr/bin/aws-rb",
Then,I open "/usr/bin/" dirctory, but couldn't find any "aws-rb" or "aws" file.

**Comment by random-ua** [comment]
You should disable SIP before installing gem. Read more http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11

**Comment by strfn** [comment]
Instead of disabling SIP you could install shenzhen in a folder not restricted by SIP
ie sudo gem instal --bin /usr/local/bin/ shenzhen
