### ISSUE TITLE
ipa distribute:fir -u USER_TOKEN -a APP_ID   error

### ISSUE THREAD

**Issue by Shawkaine** [nomad/shenzhen#320]
![6zihvjnyunx027 n4s goct](https://cloud.githubusercontent.com/assets/10775888/13515424/25edec54-e1ec-11e5-9a8e-a1f10168d5c1.jpg)
api address changed, not available now.
Also, no USER_TOKEN anymore, only API_TOKEN.

**Comment by LargeShrimp** [comment]
Me too ! I have the same error.
