### ISSUE TITLE
Why this error pop up while submitting to iTunes connect? How to resolve this? 

### ISSUE THREAD

**Issue by jacobjiangwei** [nomad/shenzhen#322]
Recently our jenkins job comes up with this error.
It was working fine before, we only did code changes, not project setting change, not new framework introduced.

I google a few, not too much information found. 
How to resolve this?

1 package(s) were not uploaded because they had problems:
11:41:00    /Users/jenkins/jenkins-slave/workspace/XXX/Package.itmsp - Error Messages:
11:41:00        The session's status is FAILED and the error description is 'failed to open ssh session. (16)'
11:41:00        ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'XXX.APP/Frameworks/Analytics.framework/Analytics' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by vrcmarcos** [comment]
The problems is also happening when trying to upload the .ipa file with Application Loader. I don't think this is a shenzhen related problem.
