### ISSUE TITLE
Can't handle spaces in .app name inside payload

### ISSUE THREAD

**Issue by silvermace** [nomad/shenzhen#323]
Hi, great tool - have noted that it seems an IPA that contains an .app target with a space in the name can't be handled by the code -- errors out

running
`sudo ipa info myapp.ipa`

results in

```
Using .app: My App.app
security: unable to open "/var/folders/d6/wt71m3s960x5_w546d0qvbv80000gn/T/d20160706-93068-sqr6ax/Payload/My" for reading: No such file or directory
undefined method `each' for nil:NilClass
```

**Comment by KrauseFx** [comment]
You might want to try [gym](https://fastlane.tools/gym) 👍

**Comment by skywinder** [comment]
@KrauseFx how can I check info about ipa via `gym`?

**Comment by KrauseFx** [comment]
Whoops, sorry, I thought this was about building the `ipa`

**Comment by skywinder** [comment]
Related with https://github.com/nomad/shenzhen/pull/273
@KrauseFx btw, it would be good feature request for `fastlane` - to got information about ipa. Probably this functionality closer to `deliver` module
