### ISSUE TITLE
Where is the Xcode archived file located? 

### ISSUE THREAD

**Issue by jacobjiangwei** [nomad/shenzhen#324]
Today we are using this to submit build automatically and we got the dSYM file in some where.

But I didn't see the archived file in Xcode Organizer.

Is there any way to get the original file? It's gonna help us identify the crash report from App Store.

Your help would be much appreciated!

**Comment by KrauseFx** [comment]
Yeah, you can use [gym](https://fastlane.tools/gym), which will store the archive in the Xcode location for further inspection 👍
