### ISSUE TITLE
Including DSYM?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [nomad/shenzhen#330]
Hello,

Crashlytics is telling us that all of our builds we're sending (via ipa distribute:crashlytics) are missing DSYM files. We're sending builds to Crashlytics with this module's "ipa distribute:crashlytics ..." command.

How do I get it to upload DSYMs as well? We see the "Blah.app.dSYM.zip" file, so the DSYM is there and accessible.

**Comment by KrauseFx** [comment]
Check out [fastlane](https://fastlane.tools) which allows you to easily build your app using [gym](https://fastlane.tools/gym) and then directly upload the `ipa` and the `dsym` to crashlytics 👍

**Comment by GeoffreyPlitt** [comment]
Will do, thanks!
