### ISSUE TITLE
Missing release comment

### ISSUE THREAD

**Issue by Sathishobs** [nomad/shenzhen#338]
I'm under the path of the valid .ipa file and start pushing build to testfairy with the API key as mentioned in the syntax. terminal prompt to enter the release notes and I did save & quit ( :wq command) after enter some notes. It's thrown an error as below comments. Please assist me to use this plugin properly. 

Laptop-001:build king$ ipa distribute:testfairy -a API_KEY
**Missing release comment**

**Comment by saxsor** [comment]
Hi, I'm having the same issue, dou you have any solution for this, or could you explain me how to avoid this issue? Thanks & Regards!
