### ISSUE TITLE
error: Unable to copy

### ISSUE THREAD

**Issue by AsTryE** [nomad/shenzhen#339]
jenkins ci,execute command:
ipa build --clean -c "Debug" -d "~/Desktop/newApp" -w "${WORKSPACE}/P2PGongXinYing.xcworkspace" -m "~/Desktop/newApp/gxyAppTest.mobileprovision" -i "iPhone Developer: ***(76VF5G63AV)" -s P2PGongXinYing --ipa "Gxyapp.ipa" no-archive
======================
errors:
+ ipa build --clean -c Debug -d '~/Desktop/newApp' -w /Users/gongxinying/.jenkins/workspace/gxypp/P2PGongXinYing.xcworkspace -m '~/Desktop/newApp/gxyAppTest.mobileprovision' -i 'iPhone Developer: ***(76VF5G63AV)' -s P2PGongXinYing --ipa Gxyapp.ipa no-archive
     xcodebuild  /Users/gongxinying/.jenkins/workspace/gxypp/P2PGongXinYing.xcworkspace
          xcrun  PackageApplication
error: Unable to copy '~/Desktop/newApp/gxyAppTest.mobileprovision' to '/var/folders/tr/x7dlnp494msd6kr46gfjklk00000gn/T/Z4NV8wif_o/Payload/P2PGongXinYing.app/embedded.mobileprovision'

Build step 'Execute shell' marked build as failure
Finished: FAILURE

~/Desktop/newApp/gxyAppTest.mobileprovision and /var/folders/tr/x7dlnp494msd6kr46gfjklk00000gn/T/Z4NV8wif_o/Payload/P2PGongXinYing.app files exists . i don know why? thanks!

**Comment by xmkevin** [comment]
I have the same problem? Anyone can help ?

**Comment by dankimio** [comment]
@xmkevin What version are you using?
