### ISSUE TITLE
Create a new version?

### ISSUE THREAD

**Issue by maxfriedrich** [nomad/shenzhen#341]
Hi! Can you create a new version of the gem? We're using a specific commit ref version at the moment to use the gem [with faraday 0.9](https://github.com/nomad/shenzhen/pull/296). I understand that this project is not really active anymore but maybe other people need this, too. Thanks! ☺️

**Comment by dankimio** [comment]
Done 👍

**Comment by maxfriedrich** [comment]
Thanks a lot @dankimio 👍
