### ISSUE TITLE
upload fir error

### ISSUE THREAD

**Issue by zypsusu** [nomad/shenzhen#343]
I get the token and appId on fir.com.  Then  I use  ipa distribute:fir -u xxxxxxxxxx -a xxxxxxxxx, get the error :    error: 784: unexpected token at 'Cannot GET /api/v2/app/info/xxxxxxxxxxxx?token=xxxxxxxxxxxx&amp;type=ios
'. Use --trace to view backtrace    
How to resolve it?

**Comment by dankimio** [comment]
@zypsusu What version are you using?

**Comment by Kitty2014** [comment]
@dankimio  same issue with zypsusu
localhost:CheckAuto3-17 uxin$ ipa distribute:fir -u 4ba2d37b19c3915f3067d7a9bafc0c5d -a CheckAuto3-0  --trace
App Version:
1
Short Version:
2
/Users/uxin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at 'Cannot GET /api/v2/app/info/CheckAuto3-0?token=4ba2d37b19c3915f3067d7a9bafc0c5d&amp;type=ios (Faraday::ParsingError)
'
	from /Users/uxin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:50:in `parse'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday-0.11.0/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/shenzhen-0.14.3/lib/shenzhen/plugins/fir.rb:29:in `get_app_info'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/shenzhen-0.14.3/lib/shenzhen/plugins/fir.rb:99:in `block (2 levels) in <top (required)>'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/uxin/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
localhost:CheckAuto3-17 uxin$

**Comment by Kitty2014** [comment]
@dankimio @zypsusu

**Comment by CaliosD** [comment]
Same issue here. Hope it can be fine soon. :)
