### ISSUE TITLE
XCode 8.3 cannot find PackageApplication

### ISSUE THREAD

**Issue by scisxuepeng** [nomad/shenzhen#348]
Everything is good until I upgrade XCode to 8.3, and I got an error like this
xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH

I googled this. It seems XCode 8.3 removed PackageApplication according to this

http://stackoverflow.com/questions/43094380/whats-the-replacement-for-xcodes-packageapplication

https://issues.jenkins-ci.org/browse/JENKINS-43163

Seems we need a fix for this?

**Comment by mexiQQ** [comment]
I meet with the same question.

**Comment by KrauseFx** [comment]
You might want to use [fastlane gym](https://fastlane.tools/gym) to build your app, as it uses the latest Xcode API. `PackageApplication` was removed with Xcode 8.3
