### ISSUE TITLE
FilePermissionError

### ISSUE THREAD

**Issue by PengJiang520** [nomad/shenzhen#350]
jiangpengdeMacBook-Pro:usr jiangpeng$ sudo gem install shenzhen
Password:
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.

**Comment by PengJiang520** [comment]
https://blog.csdn.net/z82367825/article/details/55000615

**Comment by dankimio** [comment]
@PengJiang520 This is not an issue with `shenzhen` gem.
