### ISSUE TITLE
Shenzen fails on Xcode version check when evaluating Xcode 10+

### ISSUE THREAD

**Issue by thzinc** [nomad/shenzhen#351]
The command to evaluate the current Xcode version is doing a string comparison on the Xcode version number against the string "4.0.0". This fails for Xcode 10+ because the version number "10.0.0" is evaluated as less than "4.0.0".

**Comment by thzinc** [comment]
I'll submit a PR for this issue shortly.

**Comment by dankimio** [comment]
Fixed in #351
