### ISSUE TITLE
Shenzhen requires Xcode 4 (found 10.0). Please install or switch to the latest Xcode.

### ISSUE THREAD

**Issue by dluffymonkey** [nomad/shenzhen#353]
run  `ipa build`  get error:

Shenzhen requires Xcode 4 (found 10.0). Please install or switch to the latest Xcode.

**Comment by dluffymonkey** [comment]
Xcode  Version 10.0 (10A255)

**Comment by KrauseFx** [comment]
shenzhen isn't maintained any more, I'd recommend using [fastlane](https://fastlane.tools) together with `fastlane gym` 👍
